flex:
  version: 0.5.6
  workflows:
    build:
      command: ./scripts/build.sh
    publish:
      command: ./scripts/publish.sh
    deploy:
      command: ./scripts/deploy.sh
    promote-release:
      command: jfrog rt build-promote docker-build 6.0.0 springtest-docker-stg-local
service:
  name: springtest
