apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springtest
    backstage.io/kubernetes-id: springtest
  name: springtest
  namespace: '{{ .Values.config.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springtest
        backstage.io/kubernetes-id: springtest
    spec:
      containers:
      - image: 'vad1mo/hello-world-rest'
        imagePullPolicy: IfNotPresent
        name: springtest
        resources: {}
        ports:
          - containerPort: 5050 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5050
          periodSeconds: 5
status: {}
